//! Problem 2: Even Fibonacci numbers
//!
//! Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//!
//! 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//!
//! By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

pub fn even_fibonacci_numbers(max_num: u32) -> u32 {
    let mut pair: (u32, u32) = (1, 2);
    let mut sum: u32 = 0;
    loop {
        if pair.0 > max_num {
            break;
        }

        if pair.0 % 2 == 0 {
            sum += pair.0;
        }

        pair = (pair.1, pair.0 + pair.1);
    }
    sum
}

#[cfg(test)]
mod s002_tests {
    use super::*;

    struct Test {
        result: u32,
        max_num: u32,
    }

    #[test]
    fn test_even_fibonacci_numbers() {
        let tests = [
            Test {
                result: 0,
                max_num: 0,
            },
            Test {
                result: 2,
                max_num: 2,
            },
            Test {
                result: 2,
                max_num: 3,
            },
            Test {
                result: 2,
                max_num: 4,
            },
            Test {
                result: 2,
                max_num: 5,
            },
            Test {
                result: 44,
                max_num: 89,
            },
        ];

        for test in tests.iter() {
            assert_eq!(test.result, even_fibonacci_numbers(test.max_num));
        }
    }
}
